### ISSUE TITLE
I just wanted to thank you for all of your hard work! 

### ISSUE THREAD

**Issue by b9Joker108** [ExtremeXT/exynos990#2]
I have an Australian Samsung Galaxy S20 Ultra 5G (SM-G988B) with a traditional SIM and an eSIM and a microSD port, and had to confirm that my phone was running the Exynos990 chipset with the CPU-Z Android app, because I couldn't find any onboard way to determine with certainty. I was so annoyed when I found out my device wasn't getting the OneUI 6.0 upgrade, and now I am so happy that ExtremeXT has made a custom ROM available that is compatible with my device. 

**I just wanted to thank you for all of your hard work!**

**Comment by ExtremeXT** [comment]
You're welcome! :D
